// qicaaf-ns3.cc
//
// Real ns-3 validation of QI-CAAF vs conventional per-receiver TCP ACK.
//
// Topology: star. 1 source node <-> n receiver nodes, each over an
// independent point-to-point link (real bandwidth/propagation delay,
// real DropTail queue, real per-link stochastic loss both directions).
//
// Data path: real TCP (ns-3 production stack: congestion control, RTO,
// delayed ACK, retransmission) delivers a fixed payload from source to
// each receiver via BulkSendApplication -> PacketSink.
//
// Confirmation path (QI-CAAF): once a receiver's PacketSink has received
// the full payload, the receiver sends ONE small UDP confirmation packet
// to an aggregator application co-located with the source. The aggregator
// waits for confirmations up to a round timeout, computes collective
// fidelity F = k/n, and (if F < Fth) marks the non-responding receivers
// as failed for that round (FASRO would retransmit to them next round;
// this program measures a single round, consistent with the paper's
// per-round metrics).
//
// Conventional-TCP ACK overhead is measured directly and honestly from
// ns-3's FlowMonitor: the reverse-direction (receiver->source) flow for
// each TCP connection is exactly the real ACK traffic generated by ns-3's
// real TCP stack (including delayed ACKs and duplicate ACKs caused by
// loss), not an assumption.

#include "ns3/applications-module.h"
#include "ns3/core-module.h"
#include "ns3/flow-monitor-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/point-to-point-module.h"

#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <vector>

using namespace ns3;

NS_LOG_COMPONENT_DEFINE("QICAAF");

// ---------------------------------------------------------------------
// Aggregator application (source side): implements CECSF + GADCE.
// ---------------------------------------------------------------------
class AggregatorApp : public Application
{
  public:
    AggregatorApp()
        : m_socket(nullptr),
          m_port(9000),
          m_n(0),
          m_fth(0.90),
          m_confirmed(0),
          m_confirmTime(Seconds(0))
    {
    }

    void Setup(uint16_t port, uint32_t n, double fth)
    {
        m_port = port;
        m_n = n;
        m_fth = fth;
    }

    uint32_t GetConfirmedCount() const
    {
        return m_confirmed;
    }

    double GetFidelity() const
    {
        return m_n > 0 ? static_cast<double>(m_confirmed) / m_n : 0.0;
    }

    bool GetGlobalConfirmed() const
    {
        return GetFidelity() >= m_fth;
    }

    Time GetConfirmTime() const
    {
        return m_confirmTime;
    }

    void StartRound()
    {
        m_confirmed = 0;
        m_confirmTime = Seconds(0);
        m_seen.clear();
    }

  private:
    void StartApplication() override
    {
        if (!m_socket)
        {
            m_socket = Socket::CreateSocket(GetNode(), TypeId::LookupByName("ns3::UdpSocketFactory"));
            InetSocketAddress local = InetSocketAddress(Ipv4Address::GetAny(), m_port);
            m_socket->Bind(local);
            m_socket->SetRecvCallback(MakeCallback(&AggregatorApp::HandleRead, this));
        }
    }

    void StopApplication() override
    {
        if (m_socket)
        {
            m_socket->Close();
        }
    }

    void HandleRead(Ptr<Socket> socket)
    {
        Ptr<Packet> packet;
        Address from;
        while ((packet = socket->RecvFrom(from)))
        {
            uint8_t buf[4] = {0};
            packet->CopyData(buf, std::min<uint32_t>(4, packet->GetSize()));
            uint32_t receiverId = (uint32_t)buf[0] | ((uint32_t)buf[1] << 8) |
                                   ((uint32_t)buf[2] << 16) | ((uint32_t)buf[3] << 24);
            if (m_seen.find(receiverId) == m_seen.end())
            {
                m_seen.insert(receiverId);
                m_confirmed++;
                if (GetGlobalConfirmed() && m_confirmTime == Seconds(0))
                {
                    m_confirmTime = Simulator::Now();
                }
            }
        }
    }

    Ptr<Socket> m_socket;
    uint16_t m_port;
    uint32_t m_n;
    double m_fth;
    uint32_t m_confirmed;
    Time m_confirmTime;
    std::set<uint32_t> m_seen;
};

// ---------------------------------------------------------------------
// Confirm-sender application (receiver side): fires one UDP confirm
// packet once the receiver's PacketSink has the full payload.
// ---------------------------------------------------------------------
class ConfirmSenderApp : public Application
{
  public:
    ConfirmSenderApp() : m_socket(nullptr), m_receiverId(0)
    {
    }

    void Setup(Address aggregatorAddr, uint32_t receiverId)
    {
        m_aggregatorAddr = aggregatorAddr;
        m_receiverId = receiverId;
    }

    void SendConfirm()
    {
        if (!m_socket)
        {
            m_socket = Socket::CreateSocket(GetNode(), TypeId::LookupByName("ns3::UdpSocketFactory"));
            m_socket->Connect(m_aggregatorAddr);
        }
        uint8_t buf[4];
        buf[0] = (uint8_t)(m_receiverId & 0xFF);
        buf[1] = (uint8_t)((m_receiverId >> 8) & 0xFF);
        buf[2] = (uint8_t)((m_receiverId >> 16) & 0xFF);
        buf[3] = (uint8_t)((m_receiverId >> 24) & 0xFF);
        Ptr<Packet> p = Create<Packet>(buf, 4); // 4-byte confirm payload
        m_socket->Send(p);
    }

  private:
    void StartApplication() override
    {
    }

    void StopApplication() override
    {
        if (m_socket)
        {
            m_socket->Close();
        }
    }

    Ptr<Socket> m_socket;
    Address m_aggregatorAddr;
    uint32_t m_receiverId;
};

// ---------------------------------------------------------------------
// Globals for bookkeeping across trace callbacks
// ---------------------------------------------------------------------
static std::vector<Ptr<PacketSink>> g_sinks;
static std::vector<Ptr<ConfirmSenderApp>> g_confirmApps;
static std::vector<bool> g_dataComplete;
static uint32_t g_payloadBytes = 512;

void
RxTrace(uint32_t receiverId, Ptr<const Packet> p, const Address& from)
{
    if (g_dataComplete[receiverId])
    {
        return;
    }
    if (g_sinks[receiverId]->GetTotalRx() >= g_payloadBytes)
    {
        g_dataComplete[receiverId] = true;
        g_confirmApps[receiverId]->SendConfirm();
    }
}

int
main(int argc, char* argv[])
{
    uint32_t n = 100;
    double lossRate = 0.01;
    double fth = 0.90;
    uint32_t rngRun = 1;
    std::string tcpVariant = "ns3::TcpLinuxReno";
    std::string outFile = "results.csv";
    double bandwidthMbps = 100.0;
    double delayMs = 1.0;
    uint32_t queueSize = 100;
    uint32_t delAckCount = 2;

    CommandLine cmd;
    cmd.AddValue("n", "Number of receivers", n);
    cmd.AddValue("loss", "Per-link loss rate", lossRate);
    cmd.AddValue("fth", "Fidelity threshold", fth);
    cmd.AddValue("run", "RNG run number (for replication)", rngRun);
    cmd.AddValue("tcp", "TCP variant type id", tcpVariant);
    cmd.AddValue("out", "Output CSV file", outFile);
    cmd.AddValue("bw", "Link bandwidth (Mbps)", bandwidthMbps);
    cmd.AddValue("delay", "Link one-way propagation delay (ms)", delayMs);
    cmd.AddValue("queue", "Queue size (packets)", queueSize);
    cmd.AddValue("delack", "TCP DelAckCount (1=immediate ACK, 2=delayed ACK)", delAckCount);
    cmd.Parse(argc, argv);

    RngSeedManager::SetSeed(12345);
    RngSeedManager::SetRun(rngRun);

    Config::SetDefault("ns3::TcpL4Protocol::SocketType", StringValue(tcpVariant));
    Config::SetDefault("ns3::TcpSocket::DelAckCount", UintegerValue(delAckCount));
    Config::SetDefault("ns3::TcpSocket::SegmentSize", UintegerValue(536));

    NodeContainer source;
    source.Create(1);
    NodeContainer receivers;
    receivers.Create(n);

    InternetStackHelper internet;
    internet.InstallAll();

    PointToPointHelper p2p;
    p2p.SetDeviceAttribute("DataRate", StringValue(std::to_string((uint64_t)bandwidthMbps) + "Mbps"));
    p2p.SetChannelAttribute("Delay", TimeValue(MilliSeconds((int64_t)delayMs)));
    p2p.SetQueue("ns3::DropTailQueue<Packet>", "MaxSize", StringValue(std::to_string(queueSize) + "p"));

    Ipv4AddressHelper address;
    std::vector<Ipv4InterfaceContainer> interfaces(n);

    g_sinks.assign(n, nullptr);
    g_confirmApps.assign(n, nullptr);
    g_dataComplete.assign(n, false);
    g_payloadBytes = 512;

    uint16_t sinkPort = 8080;
    uint16_t aggregatorPort = 9000;

    Ptr<Node> src = source.Get(0);

    Ptr<AggregatorApp> aggregator = CreateObject<AggregatorApp>();
    aggregator->Setup(aggregatorPort, n, fth);
    src->AddApplication(aggregator);
    aggregator->SetStartTime(Seconds(0.0));
    aggregator->SetStopTime(Seconds(10.0));

    for (uint32_t i = 0; i < n; ++i)
    {
        NodeContainer link(src, receivers.Get(i));
        NetDeviceContainer devices = p2p.Install(link);

        Ptr<RateErrorModel> em0 = CreateObject<RateErrorModel>();
        em0->SetAttribute("ErrorRate", DoubleValue(lossRate));
        em0->SetAttribute("ErrorUnit", EnumValue(RateErrorModel::ERROR_UNIT_PACKET));
        devices.Get(0)->SetAttribute("ReceiveErrorModel", PointerValue(em0));

        Ptr<RateErrorModel> em1 = CreateObject<RateErrorModel>();
        em1->SetAttribute("ErrorRate", DoubleValue(lossRate));
        em1->SetAttribute("ErrorUnit", EnumValue(RateErrorModel::ERROR_UNIT_PACKET));
        devices.Get(1)->SetAttribute("ReceiveErrorModel", PointerValue(em1));

        std::ostringstream subnet;
        subnet << "10." << (1 + (i / 250)) << "." << (i % 250) << ".0";
        address.SetBase(subnet.str().c_str(), "255.255.255.0");
        Ipv4InterfaceContainer iface = address.Assign(devices);
        interfaces[i] = iface;

        Address sinkLocalAddr(InetSocketAddress(Ipv4Address::GetAny(), sinkPort));
        PacketSinkHelper sinkHelper("ns3::TcpSocketFactory", sinkLocalAddr);
        ApplicationContainer sApp = sinkHelper.Install(receivers.Get(i));
        sApp.Start(Seconds(0.0));
        sApp.Stop(Seconds(10.0));
        Ptr<PacketSink> sink = DynamicCast<PacketSink>(sApp.Get(0));
        g_sinks[i] = sink;
        sink->TraceConnectWithoutContext("Rx", MakeBoundCallback(&RxTrace, i));

        Address sinkRemoteAddr(InetSocketAddress(iface.GetAddress(1), sinkPort));
        BulkSendHelper bulkHelper("ns3::TcpSocketFactory", sinkRemoteAddr);
        bulkHelper.SetAttribute("MaxBytes", UintegerValue(g_payloadBytes));
        ApplicationContainer bApp = bulkHelper.Install(src);
        bApp.Start(Seconds(0.01));
        bApp.Stop(Seconds(9.0));

        Ptr<ConfirmSenderApp> confirmApp = CreateObject<ConfirmSenderApp>();
        Address aggregatorAddr(InetSocketAddress(iface.GetAddress(0), aggregatorPort));
        confirmApp->Setup(aggregatorAddr, i);
        receivers.Get(i)->AddApplication(confirmApp);
        confirmApp->SetStartTime(Seconds(0.0));
        confirmApp->SetStopTime(Seconds(10.0));
        g_confirmApps[i] = confirmApp;
    }

    aggregator->StartRound();

    FlowMonitorHelper flowmonHelper;
    Ptr<FlowMonitor> monitor = flowmonHelper.InstallAll();

    Simulator::Stop(Seconds(10.0));
    Simulator::Run();

    monitor->CheckForLostPackets();
    Ptr<Ipv4FlowClassifier> classifier =
        DynamicCast<Ipv4FlowClassifier>(flowmonHelper.GetClassifier());
    std::map<FlowId, FlowMonitor::FlowStats> stats = monitor->GetFlowStats();

    uint64_t tcpDataBytesFwd = 0;
    uint64_t tcpAckBytesRev = 0;
    uint64_t tcpDataPacketsFwd = 0;
    uint64_t tcpAckPacketsRev = 0;
    uint64_t udpConfirmBytes = 0;
    uint64_t udpConfirmPackets = 0;

    for (auto& kv : stats)
    {
        Ipv4FlowClassifier::FiveTuple t = classifier->FindFlow(kv.first);
        const FlowMonitor::FlowStats& s = kv.second;
        if (t.protocol == 6) // TCP
        {
            if (t.destinationPort == sinkPort)
            {
                tcpDataBytesFwd += s.txBytes;
                tcpDataPacketsFwd += s.txPackets;
            }
            else if (t.sourcePort == sinkPort)
            {
                tcpAckBytesRev += s.txBytes;
                tcpAckPacketsRev += s.txPackets;
            }
        }
        else if (t.protocol == 17) // UDP
        {
            if (t.destinationPort == aggregatorPort)
            {
                udpConfirmBytes += s.txBytes;
                udpConfirmPackets += s.txPackets;
            }
        }
    }

    uint32_t confirmed = aggregator->GetConfirmedCount();
    double fidelity = aggregator->GetFidelity();
    bool globalOk = aggregator->GetGlobalConfirmed();
    double confirmTimeMs = aggregator->GetConfirmTime().GetSeconds() * 1000.0;

    uint32_t dataCompleteCount = 0;
    for (uint32_t i = 0; i < n; ++i)
    {
        if (g_dataComplete[i])
        {
            dataCompleteCount++;
        }
    }

    uint64_t qicaafOverheadBytes = udpConfirmBytes + 8;
    uint64_t conventionalOverheadBytes = tcpAckBytesRev;

    bool fileExists = std::ifstream(outFile).good();
    std::ofstream f(outFile, std::ios::app);
    if (!fileExists)
    {
        f << "n,loss,fth,run,tcp_variant,delack,"
             "conv_ack_bytes,conv_ack_packets,"
             "qicaaf_confirm_bytes,qicaaf_confirm_packets,"
             "data_complete_count,confirmed_count,fidelity,global_confirmed,"
             "confirm_time_ms,tcp_data_bytes_fwd,tcp_data_packets_fwd\n";
    }
    f << n << "," << lossRate << "," << fth << "," << rngRun << "," << tcpVariant << "," << delAckCount << ","
      << conventionalOverheadBytes << "," << tcpAckPacketsRev << ","
      << qicaafOverheadBytes << "," << udpConfirmPackets << ","
      << dataCompleteCount << "," << confirmed << "," << fidelity << "," << (globalOk ? 1 : 0) << ","
      << confirmTimeMs << "," << tcpDataBytesFwd << "," << tcpDataPacketsFwd << "\n";
    f.close();

    Simulator::Destroy();
    return 0;
}
